# Generated by Django 3.2.18 on 2023-07-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_auto_20230709_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='resmesdetails',
            name='mob',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
    ]
